server {
    listen 80;
    server_name tofado.com www.tofado.com;

    root /var/www/tofado;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }
}
